# Generated by Django 5.1.6 on 2025-02-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultorio_id', models.CharField(max_length=10)),
                ('medico_id', models.CharField(max_length=10)),
                ('cliente_id', models.CharField(max_length=10)),
                ('servicio_id', models.CharField(default='0', max_length=10)),
                ('precio', models.CharField(default='0', max_length=10)),
                ('fecha', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=10)),
                ('observaciones', models.TextField(max_length=200)),
                ('checkin_fecha', models.TextField(default='', max_length=20)),
                ('checkin_edad', models.TextField(default='', max_length=6)),
                ('checkin_sexo', models.TextField(default='', max_length=12)),
                ('checkin_peso', models.TextField(default='', max_length=12)),
                ('checkin_talla', models.TextField(default='', max_length=12)),
                ('checkin_presion_arterial', models.TextField(default='', max_length=12)),
                ('checkin_frecuencia_cardiaca', models.TextField(default='', max_length=12)),
                ('checkin_frecuencia_respiratoria', models.TextField(default='', max_length=12)),
                ('checkin_temperatura', models.TextField(default='', max_length=12)),
                ('checkin_resumen', models.TextField(default='', max_length=500)),
                ('checkin_exploracion_fisica', models.TextField(default='', max_length=500)),
                ('checkin_resultado_servicios_auxiliares', models.TextField(default='', max_length=500)),
                ('checkin_problemas_clinicos', models.TextField(default='', max_length=500)),
                ('checkin_indicaciones_medicas', models.TextField(default='', max_length=500)),
                ('checkin_pronostico', models.TextField(default='', max_length=500)),
                ('checkout_hora', models.TextField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('telefono1', models.CharField(max_length=200)),
                ('telefono2', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('codigopostal', models.CharField(max_length=20)),
                ('calle', models.CharField(default='', max_length=200)),
                ('numero_int', models.CharField(default='', max_length=20)),
                ('numero_ext', models.CharField(default='', max_length=20)),
                ('colonia', models.CharField(default='', max_length=20)),
                ('fecha_nac', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('estado', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_id', models.CharField(default='1', max_length=2)),
                ('disponible', models.CharField(default='N', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Consultorios_Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_id', models.CharField(max_length=2)),
                ('turno_num', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos_agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_id', models.CharField(max_length=10)),
                ('turno_num', models.IntegerField(default=1)),
                ('fecha', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=10)),
                ('hora_atencion', models.CharField(max_length=10)),
                ('mostrado', models.CharField(default='S', max_length=1)),
                ('liberado', models.CharField(default='N', max_length=1)),
                ('producto_id', models.CharField(default='6', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.consultorios')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('programa', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.menu')),
            ],
        ),
    ]
